<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title><?php echo $blocktitle ?? 'Welcome'; ?> :: Formation php avancé</title>
    <link rel="stylesheet" href="/public/css/style.css" />
</head>
<body>
<div class="container">
    <header>
        <h1><?php echo $blocktitle ?? 'Formation PHP Avancé'; ?></h1>
        <hr />
    </header>
    <nav>
        <a href="/">Accueil</a> -
        <a href="/hello">Page Hello</a> -
        <a href="/list-user">Liste des utilisateurs (sandbox)</a> -
        <a href="/design-pattern/singleton">Design Pattern : Singleton</a> -
        <a href="/design-pattern/iterator">Design Pattern : Iterator</a> -
        <a href="/design-pattern/factory">Design Pattern : Factory</a> -
        <a href="/pdf">HTML2PDF</a> -
        <a href="/orm/example">ORM : Example</a> -
        <a href="/orm">ORM : Liste</a> -
        <a href="/crypt/list">Cryptage: Liste</a> -
    </nav>
    <main>
        <?php echo $blockbody; ?>
    </main>
    <footer>
        <hr />
        <p>
            Dawan FOAD - PHP Av - Novembre 2022
        </p>
    </footer>
</div>
</body>
</html>
