<h2>Liste des utilisateurs</h2>

<table style="width:100%">
    <thead style="text-align: left">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Job</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($users as $user): ?>
    <tr>
        <td><?php echo $user['id']; ?></td>
        <td><?php echo $user['name']; ?></td>
        <td><?php echo $user['job']; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
