
<h2>Liste des produits</h2>

<table style="width:100%">
    <thead style="text-align: left">
    <tr>
        <th>ID</th>
        <th>Nom</th>
        <th>Prix</th>
        <th>Date de création</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($products as $product): ?>
    <tr>
        <td><?php echo $product->getId(); ?></td>
        <td><?php echo $product->getName(); ?></td>
        <td><?php echo $product->getPriceFormatted(); ?></td>
        <td><?php echo $product->getDateFormatted(); ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
